### PR TITLE
added license

### PR DESCRIPTION
**Pull request by zazi**

### CODE REVIEW

**Comment by knutwalker** [comment]
Can you configure the maven plugin as well, akin to our main repositories?

**Comment by zazi** [comment]
I can do so. Can I do this in another pull request, or should I add it to this one (just looking for some forthcoming manual merges ... :) ).

**Comment by knutwalker** [comment]
I'd prefer to have this one amended, if it's all the same to you.

**Comment by zazi** [comment]
here we go!

**Comment by knutwalker** [comment]
thx

**Pull request merged**
